version: "3.9"

services:
    app:
        container_name: app-bank-core-v1
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            db:
                condition: service_healthy

    nginx:
        container_name: nginx-bank-core-v1
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
        depends_on:
            app:
                condition: service_started

    db:
        container_name: mysql-bank-core-v1
        image: mysql:8.0
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3300:3306"
        networks:
            - laravel
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s

networks:
    laravel:
        driver: bridge
